# Generated by Django 3.2.12 on 2022-05-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='success',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
