# Generated by Django 3.2.12 on 2022-05-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tmp',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='user',
            name='success',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
