# Generated by Django 3.2.12 on 2022-05-18 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_num', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('acc_pwd', models.PositiveIntegerField()),
                ('acc_type', models.CharField(choices=[(0, '은행'), (1, '증권'), (2, '금')], max_length=50)),
                ('acc_name', models.CharField(max_length=20)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('acc_detail', models.CharField(choices=[(0, '입출금자유'), (1, '예금/적금/주택청약'), (2, '골드'), (3, '증권')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=20)),
                ('card_type', models.BooleanField()),
                ('card_img', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='LSTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pred', models.IntegerField()),
                ('act', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateTimeField()),
                ('trans_price', models.IntegerField()),
                ('trans_content', models.CharField(max_length=30)),
                ('trans_type', models.CharField(choices=[(0, '식비'), (1, '이동통신'), (2, '쇼핑'), (3, '문화생활'), (4, '의료'), (5, '교통비')], max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='platforms.account')),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20)),
                ('percent', models.IntegerField()),
                ('use_stand', models.TextField()),
                ('month_stand', models.TextField()),
                ('card', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='platforms.card')),
            ],
            options={
                'db_table': 'kb_platform_benefit',
            },
        ),
    ]
