# Generated by Django 3.2.12 on 2022-05-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_auto_20220519_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_detail',
            field=models.PositiveIntegerField(choices=[(0, '입출금자유'), (1, '예금/적금/주택청약'), (2, '골드'), (3, '증권')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_type',
            field=models.PositiveIntegerField(choices=[(0, '은행'), (1, '증권'), (2, '금')]),
        ),
        migrations.AlterField(
            model_name='trans',
            name='trans_type',
            field=models.PositiveIntegerField(choices=[(0, '식비'), (1, '이동통신'), (2, '쇼핑'), (3, '문화생활'), (4, '의료'), (5, '교통비')]),
        ),
    ]
